'use client';
import {useEffect,useState} from 'react';
type Item={id:string;a:string;b:string;number:number|null;closesAt:number|null;voteCount:number};
type Data={settings:{intervalHours:number};current:{number:number;closes_at:number}|null;questions:Item[]};
export default function Admin(){
 const [data,setData]=useState<Data|null>(null),[hours,setHours]=useState(24),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function load(){const r=await fetch('/api/admin');const d=await r.json() as Data & {error:string};if(!r.ok)throw Error(d.error);setData(d);setHours(d.settings.intervalHours)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function save(payload:unknown){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error:string};if(!r.ok)throw Error(d.error);await load();return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await save({action:'add',a:f.get('a'),b:f.get('b')})){form.reset();setMessage('Question added to the release queue.')}}
 return <main className="admin"><header><a className="brand" href="/">would<span>you</span>rather<i>?</i></a><span className="badge">ADMIN</span></header><h1>Question control.</h1><p>One shared question. A schedule you decide.</p><p className="error" role="alert">{error}</p><p role="status">{message}</p><div className="admin-grid"><section className="admin-box"><h2>Release interval</h2><form onSubmit={async e=>{e.preventDefault();if(await save({action:'settings',intervalHours:Number(hours)}))setMessage('Interval saved. It applies to the next question.')}}><label>A new question every<input type="number" min="1" max="8760" step="1" required value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><p>hours · Default: 24<br/>The current question keeps its original closing time.</p><button className="next" disabled={busy||!data}>Save interval</button></form>{data?.current&&<p>Current: No. {data.current.number}<br/>Closes: {new Date(data.current.closes_at).toLocaleString('en-GB',{timeZone:'Asia/Nicosia'})} (Cyprus)</p>}</section><section className="admin-box"><h2>Add a question</h2><form onSubmit={add}><label>Option A<textarea name="a" required maxLength={240} placeholder="Have the ability to…"/></label><label>Option B<textarea name="b" required maxLength={240} placeholder="Or would you rather…"/></label><button className="next" disabled={busy}>{busy?'Saving…':'Add to queue →'}</button></form></section></div><section className="admin-box queue"><h2>Question queue</h2><p>{data?.questions.filter(q=>q.number===null).length??0} questions waiting. They release in the order added.</p>{data?.questions.map(q=><article key={q.id}><span className="badge">{q.number===null?'QUEUED':q.closesAt&&q.closesAt>Date.now()?`LIVE · NO. ${q.number}`:`CLOSED · NO. ${q.number}`}</span><div><strong>{q.a}</strong><span className="queue-or">or</span><strong>{q.b}</strong></div><small>{q.voteCount} votes</small></article>)}</section></main>
}
