'use client';
import {useCallback,useEffect,useState} from 'react';
type Question={id:string;a:string;b:string;aVotes:number;bVotes:number;number:number;opensAt:number;closesAt:number;choice:number|null;serverTime:number};
export default function Page(){
 const [q,setQ]=useState<Question|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now());
 const load=useCallback(async()=>{try{let voter=localStorage.getItem('voter');if(!voter){voter=crypto.randomUUID();localStorage.setItem('voter',voter)}const r=await fetch('/api/questions?voter='+encodeURIComponent(voter));const data=await r.json() as Question & {error:string};if(!r.ok)throw Error(data.error);setQ(data);setNow(data.serverTime);setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{load();const timer=setInterval(load,30000);const refresh=()=>{if(document.visibilityState==='visible')load()};document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refresh)}},[load]);
 useEffect(()=>{if(!q)return;const delay=q.closesAt-q.serverTime;if(delay<=0)return;const timer=setTimeout(load,Math.min(delay+200,2147483647));return()=>clearTimeout(timer)},[q?.closesAt,q?.serverTime,load]);
 async function vote(choice:number){if(!q||busy||q.choice!==null||now>=q.closesAt)return;setBusy(true);setError('');try{const r=await fetch('/api/questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'vote',id:q.id,number:q.number,voter:localStorage.getItem('voter'),choice})});const data=await r.json() as {error:string;expired?:boolean;aVotes:number;bVotes:number;choice:number};if(!r.ok){if(data.expired)await load();throw Error(data.error)}setQ(old=>old?.id===q.id?{...old,...data}:old)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const total=q?q.aVotes+q.bVotes:0,reveal=q&&(q.choice!==null||now>=q.closesAt);
 return <main className="daily"><h1>WOULD YOU RATHER</h1><div className="choices" aria-busy={busy||!q}>{q?[q.a,q.b].map((option,c)=><button key={q.id+c} className={'card '+(c===0?'coral':'purple')+(q.choice===c?' selected':'')} disabled={busy||q.choice!==null||now>=q.closesAt} aria-label={option+(q.choice===c?' — your selection':'')} onClick={()=>vote(c)}><span className="option">{option}</span>{reveal&&<div className="result" aria-live="polite"><strong>{total?Math.round((c===0?q.aVotes:q.bVotes)/total*100):0}%{q.choice===c&&<span className="check" aria-label="Your choice"> ✓</span>}</strong><div className="track"><i style={{width:`${total?(c===0?q.aVotes:q.bVotes)/total*100:0}%`}}/></div></div>}</button>):[0,1].map(c=><div className={'card skeleton '+(c===0?'coral':'purple')} key={c} aria-label="Loading question"/>)}<div className="or" aria-hidden="true">OR</div></div>{q&&<div className="edition"><time dateTime={new Date(q.opensAt).toISOString()}>{new Date(q.opensAt).toLocaleDateString('en-US',{timeZone:'Asia/Nicosia',month:'long',day:'numeric',year:'numeric'})}</time><span>No. {q.number}</span></div>}{error&&<p className="error" role="alert">{error} <button className="retry" onClick={load}>Retry</button></p>}</main>
}
